spring:
  datasource:
    url: jdbc:mysql://localhost:3366/XM01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST
    username: xm01
    password: xm01aaa
    driver-class-name: com.mysql.jdbc.Driver
    # localhost:3366
    # username: root
    # password: XWClassroom20202023
    #模板引擎位置
  thymeleaf:
     cache: false
     prefix: classpath:/static/

#mybatis的相关配置
#mybatis:
  #mapper配置文件
  #mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.web.stock.bean
  #驼峰命名,暂不开启
  # configuration:
  #   map-underscore-to-camel-case: true


   
