@startuml

title  状态转移
[*]->登陆界面
注册界面->登陆界面
登陆界面->注册界面
登陆界面->用户主界面 :登录
用户主界面->用户信息界面
用户主界面->行情查询界面
用户主界面->用户资产界面
用户主界面->用户持仓界面
用户主界面->用户订单查询界面

登陆界面 :执行/验证注册界面
登陆界面 :输入/登录信息
注册界面 :执行/切换到登录
注册界面 :输入/进行注册
用户主界面 :执行/显示简单个人信息
用户主界面 :执行/跳转到行情界面
用户主界面 :执行/跳转到持仓管理界面
用户主界面 :执行/跳转到资产持有界面
用户主界面 :执行/跳转到订单查询界面
用户订单查询界面 :执行/显示用户的订单信息
用户订单查询界面 :执行/导出订单信息
用户订单查询界面 :执行/打印订单信息
用户订单查询界面 :退出/推出到主界面
用户主界面->[*] :注销
@endeml
